#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo "🔥 Running pre-push checks..."

# Run build and capture exit code
pnpm check || exit 1
pnpm build || {
  echo "❌ Build failed. Push aborted."
  exit 1
}

echo "✅ Pre-push passed. Proceeding with git push."