#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Load NVM
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
nvm use > /dev/null

echo "🔥 Running pre-push checks..."

pnpm check || exit 1
pnpm build || {
  echo "❌ Build failed. Push aborted."
  exit 1
}

echo "✅ Pre-push passed. Proceeding with git push."