name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      NPM_GH_PAT: ${{ secrets.NPM_GH_PAT }} # The Token for private npm
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install
        env:
          CI: true

      - name: Run ESLint
        run: pnpm exec eslint . --config eslint.config.js

      - name: Run Prettier Check
        run: pnpm exec prettier --check .

      - name: Type Check
        run: pnpm exec tsc --noEmit
  build:
    runs-on: ubuntu-latest
    env:
      NPM_GH_PAT: ${{ secrets.NPM_GH_PAT }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Run build
        run: pnpm run build
